### ISSUE TITLE
score only 0.1?

### ISSUE THREAD

**Issue by richcn** [x404xx/Bypass-Recaptcha-V3-HTTPX#1]
Hello,
This script generate only rc3 token with 0.1 Score? is possibile 0.3 score?

**Comment by x404xx** [comment]
> Hello,
> 
> This script generate only rc3 token with 0.1 Score? is possibile 0.3 score?

Hello,

It's unfortunate that many people are still facing this issue, which originates from Google itself. It has been causing problems for users since 2021.

![image](https://github.com/x404xx/Bypass-Recaptcha-V3-HTTPX/assets/114883816/15cf29b9-9b5e-4c1a-b0fc-f04da73580ec)
